### ISSUE TITLE
innerHTML error

### ISSUE THREAD

**Issue by mbashirim** [dipson88/treeselectjs#59]
i run example and it was ok
than i changed options to data got from database and i get this error
`treeselectjs.mjs.js:1 Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at l (treeselectjs.mjs.js:1:2410)
    at Tt (treeselectjs.mjs.js:1:13692)
    at treeselectjs.mjs.js:1:13096
    at Array.forEach (<anonymous>)
    at St (treeselectjs.mjs.js:1:12989)
    at Mt.updateValue (treeselectjs.mjs.js:1:14884)
    at new Mt (treeselectjs.mjs.js:1:16902)
    at me.Rt (treeselectjs.mjs.js:1:29632)
    at me.mount (treeselectjs.mjs.js:1:25214)
    at new me (treeselectjs.mjs.js:1:29418)`
what is this for?

**Comment by dipson88** [comment]
Hi @mbashirim, can you provide a part of the data (options) you are trying to set from db, I will try to use this data and see an error in the not minimized file.
